### ISSUE TITLE
Switch to Java 16

### ISSUE THREAD

**Issue by jvpichowski** [wuespace/telestion-core#237]
Since Java 16 officially supports records it is time for us to jump on the new train.

**Comment by jvpichowski** [comment]
We can use the toolchain configuration of gradle 6.8.3. It shouldn't be to much troubles.

https://melix.github.io/blog/2021/03/gradle-java16.html
https://docs.gradle.org/6.8.3/userguide/toolchains.html

**Comment by cb0s** [comment]
I genuinely like this proposal!

Due to the high usage of a lot of preview features for java 14/15 in our repository, it is important to check that nothing has changed in the final release but after a quick look, it doesn't seem so.

What you will have to do, if you update the code, is also to remove all the `@SuppressWarning("preview")` tags from where it was used and now is unnecessary.

**Comment by cb0s** [comment]
![grafik](https://user-images.githubusercontent.com/16071970/113050061-b9097180-91a4-11eb-9858-3aed935dd804.png)
Don't forget to update the github actions as well 😄
