### ISSUE TITLE
Database should support multiple sources

### ISSUE THREAD

**Issue by jvpichowski** [wuespace/telestion-core#314]

**Comment by pklaschka** [comment]
Closing this as it is based on potentially outdated assumptions. Please feel free to re-open (with an updated description) based on the current structure.

## Considerations for closing this
1. missing description / unclear
2. inactivity
3. database connectivity is no longer handled inside `telestion-core`, but in the extensions (that might change, but with that, the issue is at the very least not considering the current structure right now)
