### ISSUE TITLE
License and Copyright

### ISSUE THREAD

**Issue by jvpichowski** [wuespace/telestion-core#43]
We should add a license and copyright notice to the end (!) of the java files.

**Comment by cb0s** [comment]
I would propose I create a new branch and everybode posts the license at the end of each of his/her classes.

**Comment by cb0s** [comment]
Yesterday, while creating the package-info.java for the API, @fussel178 and I noticed that it is quite easy to add a `(c) WueSpace e.V.` in the last line of the java-docs. What do you think @jvpichowski, @pklaschka, is this enough?

**Comment by pklaschka** [comment]
Closing this as it is based on potentially outdated assumptions. Please feel free to re-open (with an updated description) based on the current structure.

## Considerations for closing this
1. this should be checked by the linter if we want to be consistent (and thus tracked in #518 )
2. it isn't actionable: in its current state, the issue can never be finished because there's no check to ensure consistency in newly created classes/files
3. missing use-case / advantages / reason for why to add it
